version: "2"
checks:
  file-lines:
    config:
      threshold: 10
  argument-count:
    config:
      threshold: 3
  method-complexity:
    config:
      threshold: 50
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 25
  similar-code:
      config:
        threshold: 3

exclude_patterns:
  - "tests/"

plugins:
  pylint:
    enabled: true